import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int n = in.nextInt();
        int pass = 0;
        
        for(int i = 0; i < n; i++)
            {
            for(int j=0; j< n; j++)
                {
                
            }
        }
        
        for(int i1 = 0;i1 < n; i1++)
            {
            for(int j1 = 0;j1< n; j1++)
                {
                if(i1+j1 >= n-1)
                    System.out.print('#');  
                else
                    System.out.print(" ");
            }
             
            System.out.println();
        }
       
        
    }
   
    
}